# Generated by Django 4.2.7 on 2023-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_category',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, null=True, unique=True),
        ),
    ]
