# Generated by Django 4.2.7 on 2023-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_add_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
