# Generated by Django 4.2.7 on 2023-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ReleaseDate',
            field=models.DateField(default='12-12-23'),
        ),
    ]
