# Generated by Django 4.2.7 on 2023-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians_directory', '0002_album_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='album',
            name='ReleaseDate',
            field=models.CharField(max_length=10),
        ),
    ]
