# Generated by Django 4.2.7 on 2023-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians_directory', '0003_album_rating_alter_album_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ReleaseDate',
            field=models.CharField(default='2023-12-12', max_length=10),
        ),
    ]
