# Generated by Django 4.2.7 on 2023-12-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicians_directory', '0004_alter_album_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='ReleaseDate',
        ),
    ]
