# Generated by Django 4.2.7 on 2023-12-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_alter_comment_body_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='car',
        ),
    ]
