# Generated by Django 4.2.7 on 2023-12-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_add_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Posts/media/images/'),
        ),
    ]
