# Generated by Django 4.2.7 on 2023-12-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_account_type_userbankaccount_acctp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='Acctp',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=10, verbose_name='Account Type'),
        ),
    ]
