# Generated by Django 4.2.7 on 2024-01-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0004_review_body'),
        ('Patient', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinmentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_type', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20)),
                ('appoinment_status', models.CharField(choices=[('Completes', 'Completes'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=20)),
                ('symptom', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctor.availabletime')),
            ],
        ),
    ]
